<a href="https://colab.research.google.com/github/sanjufvr/sample_project/blob/main/case_study_123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd

In [2]:
launch_url = "https://api.spacexdata.com/v4/launches"
launch_data = requests.get(launch_url).json()

In [3]:
df_launch = pd.DataFrame(launch_data)[['name','date_utc','success','details','rocket']]
df_launch

,name,date_utc,success,details,rocket
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb
...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec

In [4]:
df_launch['date_utc'] = pd.to_datetime(df_launch['date_utc'])
df_launch['year'] = df_launch['date_utc'].dt.year

## 2)load metadata

In [5]:
rocket_url = "https://api.spacexdata.com/v4/rockets"
rocket_data = requests.get(rocket_url).json()

df_rocket = pd.DataFrame(rocket_data)[['id', 'name', 'type', 'active', 'stages']]
df_rocket.rename(columns={'id': 'rocket'}, inplace=True)
df_rocket

                     rocket          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

## 3) merge

In [6]:
df_merged = pd.merge(df_launch, df_rocket, on='rocket', how='left')
df_merged

,name_x,date_utc,success,details,rocket,year,name_y,type,active,stages
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,Falcon 1,rocket,False,2
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,Falcon 1,rocket,False,2
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,Falcon 1,rocket,False,2
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,Falcon 1,rocket,False,2
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,Falcon 1,rocket,False,2
...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2
201,TTL-1,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022,Falcon Heavy,rocket,True,2
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2

## 4)

In [7]:
import numpy as np

countries = ['USA', 'Russia', 'India', 'China', 'France']
df_merged['country'] = np.random.choice(countries, size=len(df_merged))
df_merged['country']

0         USA
1      Russia
2         USA
3      Russia
4       India
        ...
200    France
201     India
202     China
203    France
204     India
Name: country, Length: 205, dtype: object

## 5)

In [8]:
import sqlite3
conn = sqlite3.connect("spacex_launches.db")
df_merged.to_sql("launches", conn, if_exists="replace", index=False)

205

## 6)

In [14]:
query1 = "SELECT country, COUNT(*) as num_launches FROM launches GROUP BY country"
print(pd.read_sql(query1, conn))

  country  num_launches
0   China            32
1  France            39
2   India            42
3  Russia            44
4     USA            48

In [15]:
query2 = "SELECT year, COUNT(*) as num_launches FROM launches GROUP BY year ORDER BY num_launches DESC LIMIT 1"
print(pd.read_sql(query2, conn))

   year  num_launches
0  2022            62

In [17]:
query3 = "SELECT name_x as mission_name, COUNT(*) as launch_count FROM launches GROUP BY mission_name ORDER BY launch_count DESC LIMIT 5"
print(pd.read_sql(query3, conn))

                mission_name  launch_count
0  ispace Mission 1 & Rashid             1
1                       ZUMA             1
2     WorldView Legion 1 & 2             1
3        Viasat-3 & Arcturus             1
4                    USSF-44             1